[tool.flake8]
ignore = "F405,W503"
max-line-length = 120

[tool.pydocstyle]
convention = "pep257"
add_ignore = "D200,D202,D300,D400,D401"

[tool.mypy]
python_version = "3.10"
exclude = [
    'env'
]
no_incremental = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_any_generics = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
allow_untyped_decorators = true
